checkoutLocation: "./forknite"
workspaceLocation: "."
tasks:
  - name: Workspace Setup
    env:  
      PROJECT_ARTIFACT_URL: 'https://github.com/etienne1911/forknite/releases/download'
      PROJECT_ARTIFACT_REL: 'r1'
      PROJECT_ARTIFACT_NAME: 'forknite-workspace-artifact'
    init: |
      wget $PROJECT_ARTIFACT_URL/$PROJECT_ARTIFACT_REL/$PROJECT_ARTIFACT_NAME.zip
      echo 'workspace artifact retrieved'
      unzip ${PROJECT_ARTIFACT_NAME}.zip
      echo 'done extracting workspace artifact'
      pwd && ls -la
      cd /workspace/$PROJECT_ARTIFACT_NAME/
      yarn
      # cd /workspace/$PROJECT_ARTIFACT_NAME/src/modules/three-experiments/ && git checkout voxels
      mv /worspace/forknite /workspace/$PROJECT_ARTIFACT_NAME/src/modules/
      ln -s /workspace/$PROJECT_ARTIFACT_NAME/src/modules/three-resources/assets/ public/
    command: |
      cd /workspace/PROJECT_ARTIFACT_NAME
      yarn run start
ports:
  - port: 3000
    onOpen: ignore
