checkoutLocation: "./forknite"
workspaceLocation: "."
tasks:
  - name: setup
    init: |
      yarn create react-app forknite-pwa --template cra-template-pwa-typescript
      cd /workspace/forknite-pwa/src/
      mkdir modules && cd modules/
      mv /workspace/forknite/ ./
      touch modules_checkout
      echo "git clone https://github.com/etienne1911/forknite.git" >> modules_checkout
      echo "git clone https://github.com/etienne1911/pwa-tools.git" >> modules_checkout
      echo "git clone https://gitlab.com/three-modules/three-core-modules.git" >> modules_checkout
      echo "git clone https://gitlab.com/three-modules/three-resources.git" >> modules_checkout
      echo "git clone https://gitlab.com/three-modules/three-experiments.git" >> modules_checkout
      sh modules_checkout
      node --experimental-json-modules ./pwa-tools/scripts/create_submodules.mjs ./modules_checkout >> ../../.gitmodules
      rm modules_checkout && mv .gitmodules ../../
      cd /workspace/forknite-pwa/src/modules/three-experiments/ && git checkout voxels
      cd /workspace/forknite-pwa/
      ln -s /workspace/forknite-pwa/src/modules/three-resources/assets/ public/
      yarn add react-router-dom react-router-dom three @types/three cannon-es &&
      yarn add sparse-octree @timohausmann/quadtree-js proj4 &&
      yarn add mousetrap @types/mousetrap
      node --experimental-json-modules ./src/modules/pwa-tools/scripts/json_cfg_patcher.mjs ./tsconfig.json '{"compilerOptions":{"target":"es2015","strict":false}}'> temp.json
      mv temp.json tsconfig.json
      node --experimental-json-modules ./src/modules/pwa-tools/scripts/json_cfg_patcher.mjs ./public/manifest.json '{"short_name":"Forknite","name":"Forknite PWA Demo","description":"Fortnite clone PWA version","start_url":"forknite/"}' > temp.json
      mv temp.json ./public/manifest.json
      sed -i 's/.\/App/.\/modules\/forknite\//' src/index.tsx
    command: |
      cd /workspace/forknite-pwa
      yarn run start
ports:
  - port: 3000
    onOpen: ignore
