checkoutLocation: "./forknite"
workspaceLocation: "."
tasks:
  - name: setup
    init: |
      yarn create react-app forknite-pwa --template cra-template-pwa-typescript
      cd /workspace/forknite-pwa/src/
      mkdir modules && cd modules/
      mv /workspace/forknite/ ./
      touch modules_checkout
      echo "git clone https://github.com/etienne1911/forknite.git" >> modules_checkout
      echo "git clone https://github.com/etienne1911/pwa-tools.git" >> modules_checkout
      echo "git clone https://gitlab.com/three-modules/three-core-modules.git" >> modules_checkout
      echo "git clone https://gitlab.com/three-modules/three-resources.git" >> modules_checkout
      echo "git clone https://gitlab.com/three-modules/three-experiments.git" >> modules_checkout
      sh modules_checkout
      node --experimental-json-modules ./pwa-tools/scripts/create_submodules.mjs ./modules_checkout >> ../../.gitmodules
      rm modules_checkout
      cd /workspace/forknite-pwa/src/modules/three-experiments/ && git checkout voxels
      cd /workspace/forknite-pwa/
      ln -s /workspace/forknite-pwa/src/modules/three-resources/assets/ public/
      yarn add react-router-dom react-router-dom three @types/three cannon-es &&
      yarn add sparse-octree @timohausmann/quadtree-js proj4 &&
      yarn add mousetrap @types/mousetrap
      export JSONPATCHER=./src/modules/pwa-tools/scripts/json_cfg_patcher.mjs
      export TSCONF='{"compilerOptions":{"target":"es2015","strict":false}}'
      export MANIFEST_PATCH='{"short_name":"Forknite","name":"Forknite PWA Demo","description":"Fortnite clone PWA version","start_url":"forknite/"}'
      node --experimental-json-modules $JSONPATCHER ./tsconfig.json "${TSCONF}" > temp.json
      mv temp.json tsconfig.json
      node --experimental-json-modules $JSONPATCHER ./public/manifest.json "${MANIFEST_PATCH}" > temp.json
      mv temp.json ./public/manifest.json
      sed -i 's/.\/App/.\/modules\/forknite\//' src/index.tsx
      export LINE_REPLACE='<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no" />'
      sed -i "/viewport/c${LINE_REPLACE}" public/index.html
      export LINE_REPLACE='<title>Forknite PWA</title>'
      sed "/\/title/c${LINE_REPLACE}" public/index.html
      export PATCH_FILE=src/modules/pwa-tools/patches/gh-pages_spa-fix.patch
      export PATCH_CONTENT=$(cat $PATCH_FILE) && echo $PATCH_CONTENT
      sed "/\/head/i${PATCH_CONTENT}" public/index.html
      cp src/modules/pwa-tools/patches/404.html public/
    command: |
      cd /workspace/forknite-pwa
      yarn run start
ports:
  - port: 3000
    onOpen: ignore
