name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: setup cra project
        run: cd /home/runner/work/forknite && 
          yarn create react-app cra-pwa --template cra-template-pwa-typescript &&
          cp -r /home/runner/work/forknite/forknite/copyme/* /home/runner/work/forknite/cra-pwa/ &&
          cp -r /home/runner/work/forknite/forknite/ /home/runner/work/forknite/cra-pwa/src/modules/
      - name: checkout external modules
        env: 
          GITLAB_USR: ${{ secrets.GITLAB_USER }}
          GITLAB_PWD: ${{ secrets.GITLAB_TOKEN }}
        run: cd /home/runner/work/forknite/cra-pwa/src/modules/ && 
          git clone https://$GITLAB_USR:$GITLAB_PWD@gitlab.com/three-modules/three-core-modules.git &&
          git clone https://$GITLAB_USR:$GITLAB_PWD@gitlab.com/three-modules/three-resources.git &&
          git clone https://$GITLAB_USR:$GITLAB_PWD@gitlab.com/three-modules/three-experiments.git
      - name: checkout packages deps
        run: cd /home/runner/work/forknite/cra-pwa/ &&
          yarn add react-router-dom three @types/three cannon-es &&
          yarn add sparse-octree @timohausmann/quadtree-js proj4 &&
          yarn add mousetrap @types/mousetrap
      - run: ln -s /home/runner/work/forknite/cra-pwa/src/modules/three-resources/assets /home/runner/work/forknite/cra-pwa/public
      - name: build web app
        run: cd /home/runner/work/forknite/cra-pwa/ &&
          CI=false REACT_APP_BASEURL="/three-experiments/" yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/forknite/cra-pwa/build/
