name: Generate Workspace

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup CRA project
        run:
          pwd && ls -la &&
          yarn create react-app . --template cra-template-pwa-typescript &&
          mkdir ./src/modules/
      - uses: actions/checkout@v2
        with:
          path: "src/modules/forknite"
      - uses: actions/checkout@v2
        with:
          repository: "etienne1911/pwa-tools"
          path: "src/modules/pwa-tools"
      - name: Include foreign modules
        env:
          GITLAB_USR: ${{ secrets.GITLAB_USER }}
          GITLAB_PWD: ${{ secrets.GITLAB_TOKEN }}
        run: cd src/modules &&
          git clone https://$GITLAB_USR:$GITLAB_PWD@gitlab.com/three-modules/three-core-modules.git
          && git clone https://$GITLAB_USR:$GITLAB_PWD@gitlab.com/three-modules/three-resources.git
          && git clone https://$GITLAB_USR:$GITLAB_PWD@gitlab.com/three-modules/three-experiments.git
          && pwd && ls -la
          && cd ./three-experiments/ && git checkout voxels
      - name: Retrieve packages deps
        run: 
          yarn add react-router-dom three @types/three cannon-es 
          && yarn add sparse-octree @timohausmann/quadtree-js proj4 
          && yarn add mousetrap @types/mousetrap
      - name: Patch/customize cra files
        env:
          MODULE_NAME: "forknite"
          JSONPATCHER: "./src/modules/pwa-tools/scripts/json_cfg_patcher.mjs"
          TSCONF_PATCH: '{"compilerOptions":{"target":"es2015","strict":false}}'
          MANIFEST_PATCH: '{"short_name":"Forknite","name":"Forknite PWA Demo","description":"Fortnite clone PWA version","start_url":"."}'
        run: 
          node --experimental-json-modules $JSONPATCHER ./tsconfig.json "${TSCONF_PATCH}" > temp.json
          && mv temp.json tsconfig.json
          && node --experimental-json-modules $JSONPATCHER ./public/manifest.json "${MANIFEST_PATCH}" > temp.json
          && mv temp.json ./public/manifest.json
          && sed -i "s/.\/App/.\/modules\/${MODULE_NAME}\//" src/index.tsx 
          && cat ./tsconfig.json && cat ./src/index.tsx && cat ./public/manifest.json
      - run: ln -s $GITHUB_WORKSPACE/src/modules/three-resources/assets public/ && ls -la public/assets/
      - name: build web app
        run: CI=false PUBLIC_URL=/forknite yarn build
      - name: Workspace artefact
        uses: actions/upload-artifact@v2
        with:
          name: workspace-artifact
          path: |
            .
            !./node_modules/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/
